apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysfits-deployment
  labels:
    app: mysfits
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mysfits
  template:
    metadata:
      labels:
        app: mysfits
    spec:
      serviceAccountName: mysfits-sa
      containers:
      - name: mysfits
        image: 200562504897.dkr.ecr.eu-west-1.amazonaws.com/eksstack-breezyrepob8e956fd-x8goxtfoylat:9d19ded1cfcaf7e48ca9e9ec8be86d99fb9e0a44
        ports:
        - containerPort: 80
        env:
        - name: DDB_TABLE_NAME
          value: "AppStack-MysfitsTable54ADD99F-1BDQX4YRWNH5C"
        - name: AWS_DEFAULT_REGION
          value: "eu-west-1"
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
          requests:
            memory: "512Mi"
            cpu: "250m"
